export const SITE_URL = 'https://localizador.conhecafarmacia.com'
export const MAIN_SITE_URL = 'https://conhecafarmacia.com'
export const CONTACT_EMAIL = 'geral@conhecafarmacia.com'
export const CONTACT_PHONE_DISPLAY = '+244 925 696 002'
export const CONTACT_WHATSAPP = '244925696002'
